CREATE TABLE `competition` (
  `id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '比赛id',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '比赛名字',
  `type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '比赛类型',
  `school_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '承办学校id',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '比赛详情',
  `start_time` bigint DEFAULT NULL COMMENT '比赛开始时间 (Unix时间戳)',
  `end_time` bigint DEFAULT NULL COMMENT '比赛结束时间 (Unix时间戳)',
  `registration_start_time` bigint DEFAULT NULL COMMENT '报名开始时间 (Unix时间戳)',
  `registration_end_time` bigint DEFAULT NULL COMMENT '报名结束时间 (Unix时间戳)',
  `payment_deadline` bigint DEFAULT NULL COMMENT '缴费截止时间 (Unix时间戳)',
  `team_info_modify_deadline` bigint DEFAULT NULL COMMENT '队伍信息修改截止时间 (Unix时间戳)',
  `competition_admin_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '比赛管理员ID',
  `invitation_link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '邀请函下载链接',
  `schedule_link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '日程表下载链接',
  `registered_teams_link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '已报名队伍信息链接',
  `paid_teams_link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '已缴费队伍信息链接',
  `travel_accommodation_link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '交通住宿等信息链接',
  `awards_link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '获奖信息链接',
  `created_at` bigint DEFAULT '0' COMMENT '创建时间',
  `updated_at` bigint DEFAULT '0' COMMENT '修改时间',
  `season` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '赛季',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='比赛表，记录所有比赛'